services:
  api:
    container_name: api
    image: event.api
    build:
      # yml directory
      context: ..
      dockerfile: ./src/EventsApp.API/Dockerfile
    depends_on:
      - postgres
    
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - events_app_postgres_data:/var/lib/postgres/data
    ports:
      - "${POSTGRES_PORT}:5468"
volumes:
  events_app_postgres_data: